#CRAFT

Data:
    train_set:
        root: findoc-dataset
        dataset_name: train_nontext_craft
        val_size: 0.1
        batch_size: 32
    test_set:
        root: findoc-dataset
        dataset_name: test_nontext_craft
        batch_size: 32

Model:
    num_in_feature: 8
    num_embedding: 256
    num_hidden_feature: 128
    dropout: 0

Optim:
    lr: 0.0001
    weight_decay: 0.0005

Train:
    epoch: 100